<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CINC | Configuration in Code</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" media="screen">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/readable/bootstrap.min.css" media="screen">
    <link rel="stylesheet" href="/css/main.css" media="screen">
  </head>